feat: defiedge token fetchers
Zapper-fi/studio pull request #1815
Opened 2022-11-29 05:46 UTC by Pranavraut033

## Description

Integrating [defiedge.io](https://defiedge.io/) token fetcher on Ethereum, Polygon, Optimism and Arbitrum.

## Checklist

- [x] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
- [ ] (optional) As a contributor, my Ethereum address/ENS is:
- [ ] (optional) As a contributor, my Twitter handle is: 

## How to test?

1. Create `.env` with `ENABLED_APPS=defiedge`
2. Run `pnpm dev` to start nest server
3. Visit dev endpoints below to get list of integrate group (strategy):
    - [polygon](http://localhost:5001/apps/defiedge/tokens?groupIds[]=strategy&network=polygon)
    - [optimism](http://localhost:5001/apps/defiedge/tokens?groupIds[]=strategy&network=optimism)
    - [arbitrum](http://localhost:5001/apps/defiedge/tokens?groupIds[]=strategy&network=arbitrum)
    - [ethereum](http://localhost:5001/apps/defiedge/tokens?groupIds[]=strategy&network=ethereum)

2022-12-06 23:01 UTC, wpoulin requested changes

2022-12-06 23:05 UTC, wpoulin commented
Here are some comments you will need to address. It will improve the readability of the code quite a lot.
I've also noticed you've added a few more contract's abi than necessary ? I'm wondering if it's because you want to add more positions in the future which will require those contracts ?

2022-12-09 07:08 UTC, Pranavraut033 commented
Thanks @wpoulin for reviewing the PR. We will make the changes accordingly.

2022-12-12 04:29 UTC, Pranavraut033 commented on src/apps/defiedge/types/defiedge.types.ts
> +export interface Strategy {
removed unused types

2022-12-12 04:29 UTC, Pranavraut033 commented on src/apps/defiedge/common/defiedge.strategy.token-fetcher.ts
> +    const strategies = await axios.get<Strategy[]>(endpoint).then(({ data }) => data);
Code extracted to a function in utils

2022-12-12 04:32 UTC, Pranavraut033 commented on src/apps/defiedge/common/defiedge.strategy.token-fetcher.ts
> +                  symbol: t.symbol,
I have added getBaseToken function to create a BaseToken object if the token is not available in the getBaseTokenPrices array

2022-12-12 14:46 UTC, Pranavraut033 commented
Hello @wpoulin, I have updated the branch with mentioned changes, please review it and let me know if there are any changes.

Thanks

2022-12-13 17:28 UTC, wpoulin commented on src/apps/defiedge/common/defiedge.strategy.token-fetcher.ts
> +        const token1 = baseTokenAddressToDetails[strategy.token1.id.toLowerCase()];
Here's what you can do
```
const baseTokens = await this.appToolkit.getBaseTokenPrices(network);
const token0 = baseTokens.find(x => x.address === strategy.token0.id.toLowerCase())
const token1 = baseTokens.find(x => x.address === strategy.token1.id.toLowerCase())
```

You don't need to change the shape of `baseTokens`

2022-12-13 17:28 UTC, wpoulin commented on src/apps/defiedge/common/defiedge.strategy.token-fetcher.ts
> +    const appTokens = await Promise.allSettled(
Promise.allSettled isn't necessary, you can replace with `.all`

2022-12-13 17:28 UTC, wpoulin commented on src/apps/defiedge/common/defiedge.strategy.token-fetcher.ts
> +          symbol: strategy.title,
I suggest you get the symbol from the contract and do no overwrite it

2022-12-13 17:28 UTC, wpoulin commented on src/apps/defiedge/common/defiedge.strategy.token-fetcher.ts
> +    return appTokens.map(e => (e.status == 'fulfilled' ? e.value : null)).filter(filterNulls);
Using `Promise.all`, you will be able to do _.compact(appTokens)

2022-12-13 17:28 UTC, wpoulin commented on src/apps/defiedge/utils/index.ts
> +export async function getDefiStrategies(network: Network) {
In order to increase scallability and performance, you could `@Cache` the response. 
Here's an example : `UnipilotVaultDefinitionsResolver`

2022-12-16 21:32 UTC, wpoulin approved these changes

2022-12-17 01:04 UTC, merged